RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = yes
MOUSEKEY_ENABLE  = yes  # Mouse keys(+4700)
NKRO_ENABLE      = yes # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
AUTO_SHIFT_ENABLE = no
LEADER_ENABLE 			   = yes
TAP_DANCE_ENABLE		   = yes
EXTRAKEY_ENABLE            = yes
EXTRAFLAGS += -flto
